core/urls.py
from django.conf.urls import url

from core import views


urlpatterns = [
        url(r'^$', views.landing_provider, name='core'),
        url(r'^home/$', views.home),
        url(r'^painel/$', views.dashboard_view, name='panel'),
        url(r'^meu-perfil/$',
                              views.profile_edit,
                              name='profile_edit'),
        url(r'^minhas-configuracoes/$',
                              views.configuration_professional_edit,
                              name='configuration_index'),
        url(r'^meus-solciitacoes-servicos/$',
                              views.solicitations,
                              name='solicitations_index'),
        url(r'^novo-anuncio/$',
                              views.ad_new,
                              name='ad_new'),
        ]

profissade/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from social_django import urls as social_urls

from core import urls as core_urls
from accounts import urls as accounts_urls
from accounts.views import LoginView
from business.views import profile_public
from presentations.views import InviteView

urlpatterns = [
    # Administração Geral
    url(r'^management/', include(admin.site.urls)),

    # Captação de leads profissionais
    url(r'^profissional/', TemplateView.as_view(template_name='home.html'),
                            name='provider'),
    url(r'^pre-cadastro/sucesso/$',
        TemplateView.as_view(template_name='success.html'),
                             name='invite_success'),
    url(r'^pre-cadastro/$', InviteView.as_view(), name='invite'),

    # root do sistema
    url(r'', include(core_urls, namespace='root')),

    # Perfil público
    url(r'^perfil/$', profile_public),

    # Rotas de contas do usuário
    url(r'^conta/', include(accounts_urls, namespace='accounts')),
    url(r'^prestador/', include(core_urls, namespace='providers')),
    url(r'^contas/',include('allauth.urls')),
    url(r'^usuario/sair/$', logout,
        {'next_page': '/'}, name='logout'),
    url(
        r'^usuario/identifique-se/$',
        LoginView.as_view(template_name='accounts/login.html'),
        name='login',
        kwargs={'template_name': 'accounts/login.html'}
        ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

accounts/models.py
import re

from django.db import models
from django.core import validators
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import (UserManager, AbstractBaseUser,
                                        PermissionsMixin, Permission)

from accounts.helpers import (GENDER_CHOICES, STATUS_DOCUMENTS,
                              PROVIDER_CHOICES)


class UserManager(UserManager):

    def create_user(self, email, password=None):
        """
        Create a user commom with client permissions
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Create a superadmin on system
        """
        user = self.create_user(email, password=password)
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user



class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        'Apelido / Usuário', max_length=255, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    email = models.EmailField(verbose_name='E-mail', unique=True)
    professional = models.BooleanField(default=False, blank=False, null=False,
                                   verbose_name='É profissional?',
                                   choices=PROVIDER_CHOICES)
    is_staff = models.BooleanField(verbose_name='Equipe', default=False)
    is_active = models.BooleanField(verbose_name='Ativo', default=True)
    date_joined = models.DateTimeField(auto_now_add=True,
                                       verbose_name='Data de entrada')

    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name='Criado em')
    updated_at = models.DateTimeField(auto_now=True,
                                      verbose_name='Atualizado em')

    USERNAME_FIELD = 'email'

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.email or self.username


    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email



# model to Profile User
class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile',
                                on_delete=models.CASCADE)
    slug = models.CharField(max_length=255, blank=True, null=True,
                            verbose_name='Apelido', unique=True)
    first_name = models.CharField(max_length=250, blank=True, null=False,
                                  verbose_name='Primeiro Nome')
    last_name = models.CharField(max_length=250, blank=True, null=False,
                                  verbose_name='Sobrenome')
    avatar = models.ImageField(upload_to='profile_avatar/',
                               verbose_name='Avatar')
    skin = models.ImageField(upload_to='profile_skin/',
                               verbose_name='Skin', null=False, blank=True)
    bio = models.TextField(max_length=500, verbose_name='Bio',
                           blank=True, null=False)
    location = models.CharField(max_length=30, verbose_name='Localização',
                                blank=True, null=False)
    birth_date = models.DateField(null=True, blank=True,
                                  verbose_name='Data de Nascimento')
    gender = models.CharField(blank=True, null=True, max_length=100,
                              choices=GENDER_CHOICES, verbose_name='Eu sou')
    """
        Personal Data

    """
    cpf = models.CharField(max_length=20, blank=True,
                           null=True, verbose_name='CPF')
    rg = models.CharField(max_length=20, blank=True,
                          null=True, verbose_name='RG')
    phone_number = models.CharField(max_length=20, blank=True,
                                    null=True, verbose_name='Telefone')
    whatsapp = models.CharField(max_length=20, blank=True,
                                null=True, verbose_name='Whatsapp')
    telegram = models.CharField(max_length=2, blank=True,
                                null=True, verbose_name='Telegram')
    facebook = models.CharField(max_length=500, blank=True, null=True,
                                verbose_name='Link do seu perfil ou página')
    """
        Location Data

    """
    zipcode = models.CharField(max_length=10, blank=True, null=True,
                               verbose_name='CEP')
    country = models.CharField(max_length=20, blank=True, null=True,
                               verbose_name='País', default='Brasil')
    state = models.CharField(max_length=100, blank=True, null=True,
                             verbose_name='Estado')
    city = models.CharField(max_length=255, blank=True, null=True,
                            verbose_name='Cidade')
    address = models.CharField(max_length=500, blank=True, null=True,
                               verbose_name='Endereço')
    address_number = models.CharField(max_length=10, blank=True, null=True,
                                      verbose_name='Número')
    address_remark = models.CharField(max_length=500, blank=True, null=True,
                                      verbose_name='Complemento')
    townhouse = models.CharField(max_length=255, blank=True, null=True,
                                 verbose_name='Bairro')
    """
        Data Job

    """
    provider = models.BooleanField(default=False, blank=True, null=False,
                                   verbose_name='Prestador de serviço?',
                                   choices=PROVIDER_CHOICES)

    def completed_profile(self):
        if self.first_name and self.last_name:
            return True
        else:
            return False

    def has_avatar(self):
        if not self.avatar:
            return False


    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfis'

    def __str__(self):
        return '{} {}'.format(self.user.profile.first_name,
                              self.user.profile.last_name)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

# model to documents profile
class Document(models.Model):
    profile = models.ForeignKey(Profile, blank=False, null=False,
                                on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='documents_profiles/', blank=False,
                                null=False, verbose_name='Foto do documento')
    selfie_document = models.ImageField(upload_to='selfies_documents/',
                                        blank=False, null=False,
                                        verbose_name='Selfie com o documento')
    status = models.BooleanField(default=False, choices=STATUS_DOCUMENTS,
                                 verbose_name='Status')

profissade/templates/base.html
{% load staticfiles  %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'core/icons/apple-icon-57x57.png'%}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'core/icons/apple-icon-60x60.png'%}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'core/icons/apple-icon-72x72.png'%}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'core/icons/apple-icon-76x76.png'%}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'core/icons/apple-icon-114x114.png'%}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'core/icons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'core/icons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'core/icons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'core/icons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'core/icons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'core/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'core/icons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'core/icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'core/icons/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'core/icons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
  <link rel="stylesheet" href="{% static 'core/css/vendor/tooltipster.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/vendor/owl.carousel.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
	<!-- favicon -->
	<link rel="icon" href="favicon.ico">
  <title>profissa.de | {% block title  %} {% endblock %}</title>
</head>
<body>
{% block content  %}{% endblock %}

<svg style="display: none;">	
	<symbol id="svg-arrow" viewBox="0 0 3.923 6.64014" preserveAspectRatio="xMinYMin meet">
		<path d="M3.711,2.92L0.994,0.202c-0.215-0.213-0.562-0.213-0.776,0c-0.215,0.215-0.215,0.562,0,0.777l2.329,2.329
			L0.217,5.638c-0.215,0.215-0.214,0.562,0,0.776c0.214,0.214,0.562,0.215,0.776,0l2.717-2.718C3.925,3.482,3.925,3.135,3.711,2.92z"></path>
	</symbol>
</svg>
<svg style="display: none;">
	<symbol id="svg-star" viewBox="0 0 10 10" preserveAspectRatio="xMinYMin meet">
		<polygon points="4.994,0.249 6.538,3.376 9.99,3.878 7.492,6.313 8.082,9.751 4.994,8.129 1.907,9.751
	2.495,6.313 -0.002,3.878 3.45,3.376 "></polygon>
	</symbol>
</svg>
<svg style="display: none;">
	<symbol id="svg-plus" viewBox="0 0 13 13" preserveAspectRatio="xMinYMin meet">
		<rect x="5" width="3" height="13"></rect>
		<rect y="5" width="13" height="3"></rect>
	</symbol>
</svg>
<!-- jQuery -->

<script src="{% static 'core/js/vendor/jquery-3.1.0.min.js' %}"></script>
<!-- Tooltipster -->
<script src="{% static 'core/js/vendor/jquery.tooltipster.min.js' %}"></script>
<!-- Owl Carousel -->
<script src="{% static 'core/js/vendor/owl.carousel.min.js' %}"></script>
<!-- Tweet -->
<script src="{% static 'core/js/vendor/twitter/jquery.tweet.min.js' %}"></script>
<!-- xmAlerts -->
<script src="{% static 'core/js/vendor/jquery.xmalert.min.js' %}"></script>
<!-- Side Menu -->
<script src="{% static 'core/js/side-menu.js' %}"></script>
<!-- Home -->
<script src="{% static 'core/js/home.js' %}"></script>
<!-- Tooltip -->
<script src="{% static 'core/js/tooltip.js' %}"></script>
<!-- User Quickview Dropdown -->
<script src="{% static 'core/js/user-board.js' %}"></script>
<!-- Home Alerts -->
<script src="{% static 'core/js/home-alerts.js' %}"></script>
<!-- Footer -->
<script src="{% static 'core/js/footer.js' %}"></script>
<script src="{% static 'core/js/jquery.maskedinput.js' %}"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>
jQuery(function($){
   $("#id_birth_date").mask("99/99/9999");
   $("#id_phone_number").mask("(99) 99999-9999");
   $("#id_whatsapp").mask("(99) 99999-9999");
   $("#id_cpf").mask("999.999.999-99");
});

</script>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <script>
        $(document).ready(function () {
            toastr.success('{{ message }}');
        });
    </script>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>

profissade/templates/base_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'core/icons/apple-icon-57x57.png'%}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'core/icons/apple-icon-60x60.png'%}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'core/icons/apple-icon-72x72.png'%}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'core/icons/apple-icon-76x76.png'%}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'core/icons/apple-icon-114x114.png'%}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'core/icons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'core/icons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'core/icons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'core/icons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'core/icons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'core/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'core/icons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'core/icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'core/icons/manifest.json' %}">
    <meta name="msapplication-TileImage" content="{% static 'core/icons/ms-icon-144x144.png' %}">
	<!-- favicon -->
  <title>profissa.de | {% block title  %}{% endblock %}</title>
</head>
<body>
  {% block content  %}{% endblock  %}
  <!-- SVG PLUS -->
<svg style="display: none;">
	<symbol id="svg-plus" viewBox="0 0 13 13" preserveAspectRatio="xMinYMin meet">
		<rect x="5" width="3" height="13"/>
		<rect y="5" width="13" height="3"/>
	</symbol>
</svg>
<!-- /SVG PLUS -->
<!-- jQuery -->
<script src="{% static 'core/js/vendor/jquery-3.1.0.min.js' %}"></script>
<!-- XM Pie Chart -->
<script src="{% static 'core/js/vendor/jquery.xmpiechart.min.js' %}"></script>
<!-- Side Menu -->
<script src="{% static 'core/js/side-menu.js' %}"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<!-- Dashboard Header -->
<script src="{% static 'core/js/dashboard-header.js' %}"></script>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <script>
        $(document).ready(function () {
            toastr.success('{{ message }}');
        });
    </script>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>

profissade/templates/base_landing.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Profissa.de | {% block title %}{% endblock %}</title>
  <!-- CSS  -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'core/icons/apple-icon-57x57.png'%}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'core/icons/apple-icon-60x60.png'%}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'core/icons/apple-icon-72x72.png'%}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'core/icons/apple-icon-76x76.png'%}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'core/icons/apple-icon-114x114.png'%}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'core/icons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'core/icons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'core/icons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'core/icons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'core/icons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'core/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'core/icons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'core/icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'core/icons/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'core/icons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'landing/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'landing/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
  {% block content  %}{% endblock  %}
</body>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'landing/js/materialize.js' %}"></script>
  <script src="{% static 'landing/js/init.js' %}"></script>
</body>
</html>

profissade/templates/home.html
{% extends 'base_landing.html' %}
{% block title %} a melhor plataforma focada em prestadores de serviços{% endblock %}
{% load static  %}
{% block content %}
<nav class="light-white lighten-1" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="" class="brand-logo">
          <img src="{% static 'landing/images/logo_full.png' %}" style="width:200px;">
      </a>
      <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'invite' %}" class="btn-large profissa-red">Pré-cadastro</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
          <li><a href="{% url 'invite' %}">Pré-cadastro</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h2 class="header center profissa-text">Prepare-se para conhecer seus novos clientes</h2>
      <div class="row center">
        <h5 class="header col s12 light profissa-text">
          Nossa missão é crescer e cultivar o maior mercado digital do mundo, um lugar onde as pessoas podem encontrar e contratar qualquer serviço que precisam e criar qualquer negócio que sonhe. Como profissional, seu trabalho é inspirado pelo sucesso de nossos usuários e pela celebração de seu próprio crescimento pessoal. Junte-se a nós.
        </h5>
      </div>
      <div class="row center">
      </div>
      <br><br>

    </div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-red-text"><i class="material-icons">add_to_queue</i></h2>
            <h5 class="center">Exclusividade</h5>

            <p class="light">
              Aproveite a exclusividade de uma plataforma com foco em prestadores de serviços, não dispute espaço com produtos e outros tipos de anúncios.
            </p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-red-text"><i class="material-icons">lock_outline</i></h2>
            <h5 class="center">Segurança</h5>

            <p class="light">
              Todos os usuários da plataforma passam por uma validação de identificação, essa prática mantém a comunidade segura e permite que todos os usuários negociem com confiança.
            </p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-red-text"><i class="material-icons">assignment</i></h2>
            <h5 class="center">Agendamentos Online</h5>

            <p class="light">Os agendamentos podem ser feitos por seus clientes, pela web ou pelo celular. Eles possuem acesso a sua agenda de atendimento, escolher uma data e horário disponível e agendar o seu serviço. Você confirma ou reagenda. Simples assim!</p>
          </div>
        </div>
      </div>

    </div>
    <br><br>
  </div>
  <footer class="page-footer white">
    <div class="footer-copyright">
      <div class="container">
        <center>
        <div class="text-center center-block">
            <br />
                <a href="https://www.facebook.com/profissade"><i class="fa fa-facebook-square fa-3x social"></i></a>
	              <a href="mailto:contato@profissa.de"><i class="fa fa-envelope-square fa-3x social"></i></a>
            </div>
          </center>
        <center><span style="color:white; font-size:12px;">Profissa.de - A melhor plataforma para prestadores de serviços - 2017</span></center>
      </div>
    </div>
  </footer>

{% endblock  %}

profissade/templates/success.html
{% extends 'base_landing.html' %}
{% load static %}
{% block title  %}Pré-convite realizado com sucesso{% endblock %}
{% block content  %}
<br /><br /><br />
<div class="container">

    <center>
    <div class="row">
      <div class="col s12 ">
        <img src="{% static 'landing/images/logo_full.png' %}" style="wmargin-top:90px; width:200px;">
        <div class="card-panel profissa-red">
          <span class="white-text">
            Seu pré-cadastro foi realizado com sucesso!<br />
            Em breve encaminharemos por email o seu convite!
          </span>
        </div>
      </div>
    </div>
    </center>

  </div>
{% endblock  %}