accounts/urls.py
from django.conf.urls import url

from .views import (RegisterView, UpdateProfileView)


urlpatterns = [
    url(r'^cadastre-se/$', RegisterView.as_view(),
        name='register'),
    url(r'^atualizar-perfil/$', UpdateProfileView.as_view(),
        name='update_profile'),
]

core/urls.py
from django.conf.urls import url

from core import views


urlpatterns = [
        url(r'^$', views.landing_provider, name='core'),
        url(r'^home/$', views.home),
        url(r'^painel/$', views.dashboard_view, name='panel'),
        url(r'^meu-perfil/$',
                              views.profile_edit,
                              name='profile_edit'),
        url(r'^minhas-configuracoes/$',
                              views.configuration_professional_edit,
                              name='configuration_index'),
        url(r'^meus-solciitacoes-servicos/$',
                              views.solicitations,
                              name='solicitations_index'),
        url(r'^novo-anuncio/$',
                              views.ad_new,
                              name='ad_new'),
        ]

profissade/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from social_django import urls as social_urls

from core import urls as core_urls
from accounts import urls as accounts_urls
from accounts.views import LoginView
from business.views import profile_public
from presentations.views import InviteView

urlpatterns = [
    # Administração Geral
    url(r'^management/', include(admin.site.urls)),

    # Captação de leads profissionais
    url(r'^profissional/', TemplateView.as_view(template_name='home.html'),
                            name='provider'),
    url(r'^pre-cadastro/sucesso/$',
        TemplateView.as_view(template_name='success.html'),
                             name='invite_success'),
    url(r'^pre-cadastro/$', InviteView.as_view(), name='invite'),

    # root do sistema
    url(r'', include(core_urls, namespace='root')),

    # Perfil público
    url(r'^perfil/$', profile_public),

    # Rotas de contas do usuário
    url(r'^conta/', include(accounts_urls, namespace='accounts')),
    url(r'^prestador/', include(core_urls, namespace='providers')),
    url(r'^contas/',include('allauth.urls')),
    url(r'^usuario/sair/$', logout,
        {'next_page': '/'}, name='logout'),
    url(
        r'^usuario/identifique-se/$',
        LoginView.as_view(template_name='accounts/login.html'),
        name='login',
        kwargs={'template_name': 'accounts/login.html'}
        ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

solicitations/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import EMPTY_VALUES
from django.forms import ModelForm, widgets
from django.utils.translation import ugettext as _
from django.forms.utils import ErrorList
import re


from core.models import (Configuration, Ad, Professional)
from accounts.models import (Profile)


class DateInput(forms.DateInput):
    input_type = 'date'


# Form para Profile
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = [
                'gender',
                'first_name',
                'last_name',
                'cpf',
                'birth_date',
                'phone_number',
                'whatsapp',
                ]


# Form para configurações do profissional
class ConfigurationForm(ModelForm):


    def __init__(self, *args, **kwargs):
        super(ConfigurationForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs['placeholder'] =\
                "Um título legal para seu negócio"
        self.fields['url'].widget.attrs['placeholder'] =\
                "Um nome para link de seu Perfil"

    class Meta:
        model = Configuration
        fields = ['title', 'skin', 'category', 'url']


class AdForm(ModelForm):

    class Meta:
        model = Ad
        fields = ['title', 'short_description', 'category', 'body']



class ProfessionalForm(ModelForm):

    class Meta:
        model = Professional
        fields = [
                'category',
                'title',
                'description',
                'skills',
                'curriculum',
                'video',
                'main_address',
                'budget_is_paid',
                'base_price',
                'price_shit',
                'price_detail',
                'budget_free',
                'picture',
                'skin',
                ]

core/views.py
from django.shortcuts import (render, redirect)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.http.response import (HttpResponseRedirect, Http404)
from django.core.urlresolvers import (reverse, reverse_lazy)

from accounts.models import Profile
from core.models import (Configuration, Ad, Professional)
from core.forms import (ProfileForm, ConfigurationForm, AdForm,
                        ProfessionalForm)

# view root do sistema
class LandingProviderView(TemplateView):
    template_name = 'root.html'

    def get_context_data(self, **kwargs):
        context = super(LandingProviderView, self).get_context_data(**kwargs)
        context['profissas'] = ['Antonio', 'Mariana', 'Rubiana', 'Alander']
        return context

landing_provider = LandingProviderView.as_view()


def home(request):
    return render(request, 'landing.html')


# view para o painel de controle do usuário
@login_required
def dashboard_view(request):
    try:
        complete_profile = request.user.profile.completed_profile()
        has_avatar = request.user.profile.has_avatar()
    except:
        raise Http404()
    context = {
            'complete_profile': complete_profile,
            'has_avatar': has_avatar
            }
    return render(request, 'dashboard.html', context)


# view para edição de profile do usuario
@login_required
def profile_edit(request):
    if Profile.objects.filter(user=request.user.pk).count():
        p = Profile.objects.filter(user=request.user.pk)[:1].get()
    else:
        p = Profile()
        p.user = request.user.pk
    if request.method == 'GET':
        form = ProfileForm(instance=p)
        context = {
                    'form': form,
                }
        return render(request,'profile.html', context)
    elif request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=p)
        if form.is_valid():
            form.save()
            messages.success(request, 'Perfil atualizado com sucesso!')
            return redirect('root:profile_edit')
        return render(request, 'profile.html', {'form':form})



# view para editar configurações do perfil de usuário
@login_required
def configuration_professional_edit(request):
    if Configuration.objects.filter(provider=request.user.profile).count():
        c = Configuration.objects.filter(provider=request.user.profile)[:1]\
                                         .get()
    else:
        c = Configuration()
    c.provider = request.user.profile

    if request.method == 'GET':
        form = ConfigurationForm(instance=c)
        context = {
                    'form': form,
                }
        return render(request,'providers/configuration_professional.html',
                      context)
    elif request.method == 'POST':
        form = ConfigurationForm(request.POST, request.FILES, instance=c)
        if form.is_valid():
            form.save()
            messages.success(request, 'Configuração atualizada com sucesso!')
            return redirect('root:configuration_index')
        return render(request, 'providers/configuration_professional.html',
                      {'form':form})


@login_required
def solicitations(request):
    try:
        user = Profile.objects.get(user=request.user.pk)
        ads_count = Ad.objects.filter(user=user.pk).count()
        context = {
                'ads_count': ads_count
                }
    except:
        raise Http404()

    return render(request, 'solicitations.html', context)



@login_required
def ads(request):
    try:
        user = Profile.objects.get(user=request.user.pk)
        ads_count = Ad.objects.filter(user=user.pk).count()
        context = {
                'ads_count': ads_count
                }
    except:
        raise Http404()

    return render(request, 'clients/ads_index.html', context)


@login_required
def ad_new(request):
    if Professional.objects.filter(user=request.user.pk).count():
        p = Professional.objects.filter(user=request.user.pk)[:1].get()
    else:
        p = Professional()
        p.users_professional = request.user.pk
    if request.method == 'GET':
        form = ProfessionalForm(instance=p)
        context = {
                    'form': form,
                }
        return render(request,'ad_new.html', context)
    elif request.method == 'POST':
        form = ProfessionalForm(request.POST, request.FILES, instance=p)
        if form.is_valid():
            form.save()
            messages.success(request, 'Anúncio criado com sucesso!')
            return redirect('root:ad_new')
        return render(request, 'ad_new.html', {'form':form})

solicitations/views.py
from django.shortcuts import render

# Create your views here.

core/templates/ad_new.html
{% extends 'base.html'  %}
{% load staticfiles  %}
{% block title  %} Seu painel de controle{% endblock %}
{% block content  %}

  {% include 'header.html'  %}

<div class="section-wrap">
		<div class="section">
			<!-- CONTENT -->
			<div class="content">
				<!-- HEADLINE -->
				<div class="headline secondary">
          <h4>Anuncie seu serviço</h4>
					<!-- VIEW SELECTORS -->
					<div class="view-selectors">
					</div>
					<!-- /VIEW SELECTORS -->
					<div class="clearfix"></div>
				</div>
				<!-- /HEADLINE -->

				<!-- PRODUCT SHOWCASE -->
				<div class="product-showcase">
					<!-- PRODUCT LIST -->
					<div class="product-list grid column3-4-wrap">
            <div class="thread">
					<!-- THREAD TITLE -->
					<div class="thread-title pinned">
            <p class="text-header">Conte para todos as suas habilidades</p><br />
            {% if messages %}
              {% for message in messages %}
              <div class="alert-{{ message.tags }}">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                {{ message  }}
              </div>
              {% endfor %}
            {% endif %}

            <form method="POST" enctype="multipart/form-data" class="profile-info-form">
              {% csrf_token %}
              {% for error in form.non_field_errors  %}
              <div class="alert alert-danger">
                {{ error  }}
              </div>
              {% endfor  %}

              {% for hidden in form.hidden_fields %}
              {{ hidden }}
              {% endfor %}
              {{ form  }}
              <br /><br />
                <button class="button mid-short primary">Salvar alterações</button>
              </form>
					</div>
					<!-- /THREAD TITLE -->
					<!-- /COMMENTS -->
				</div>
					</div>
					<!-- /PRODUCT LIST -->
				</div>
				<!-- /PRODUCT SHOWCASE -->

				<div class="clearfix"></div>

			</div>
			<!-- CONTENT -->

      {% include 'sidebar.html' %}

		</div>
	</div>
	<!-- FOOTER -->
	<footer>
		<!-- FOOTER TOP -->
		<div id="footer-top-wrap">
			<div id="footer-top">
				<!-- COMPANY INFO -->
				<div class="company-info">
					<figure class="logo small">
                        <img src="{% static 'core/images/logo_full.png' %}" alt="logo-small">
					</figure>
					<p>Nós vamos mostrar o caminho para inovar a busca para encontrar profissionais de forma clara e segura que vão deixar sua casa perfeita.</p>
					<!-- SOCIAL LINKS -->
					<ul class="social-links">
						<li class="social-link fb">
							<a href="https://www.facebook.com/profissade"></a>
						</li>
					</ul>
					<!-- /SOCIAL LINKS -->
                    <div class="link-info">
					<!-- /LINK LIST -->
				</div>
				</div>
				<!-- /COMPANY INFO -->
                <div class="link-info">
					<p class="footer-title">Nossa comunidade</p>
					<!-- LINK LIST -->
					<ul class="link-list">
						<li class="link-item">
							<div class="bullet"></div>
							<a href="">Quem somos?</a>
						</li>
						<li class="link-item">
							<div class="bullet"></div>
							<a href="">Como funciona?</a>
						</li>
						<li class="link-item">
							<div class="bullet"></div>
							<a href="">Quem são os profissionais?</a>
						</li>
						<li class="link-item">
							<div class="bullet"></div>
							<a href="blog-v1.html">Confiança e Segurança</a>
						</li>
					</ul>
					<!-- /LINK LIST -->
				</div>
			</div>
		</div>
		<!-- /FOOTER TOP -->

		<!-- FOOTER BOTTOM -->
		<div id="footer-bottom-wrap">
			<div id="footer-bottom">
				<p>profissa.de - A melhor plataforma para profissionais de casa & construção - 2017</p>
			</div>
		</div>
		<!-- /FOOTER BOTTOM -->
	</footer>
	<!-- /FOOTER -->
{% endblock %}

core/templates/dashboard.html
{% extends 'base.html'  %}
{% load staticfiles  %}
{% block title  %} Seu painel de controle{% endblock %}
{% block content  %}

  {% include 'header.html'  %}

<div class="section-wrap">
		<div class="section">
			<!-- CONTENT -->
			<div class="content">
				<!-- HEADLINE -->
				<div class="headline secondary">
          <h4>Seu painel de controle</h4>
					<!-- VIEW SELECTORS -->
					<div class="view-selectors">
					</div>
					<!-- /VIEW SELECTORS -->
					<div class="clearfix"></div>
				</div>
				<!-- /HEADLINE -->

				<!-- PRODUCT SHOWCASE -->
				<div class="product-showcase">
					<!-- PRODUCT LIST -->
					<div class="product-list grid column3-4-wrap">
            <div class="thread">
					<!-- THREAD TITLE -->
					<div class="thread-title pinned">
            <p class="text-header">Notificações</p><br />
            {% if complete_profile == False %}
            <div class="alert-warning">
              <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
              Por favor, complete o seu perfil clicando <a href="{% url 'root:profile_edit' %}" >aqui</a>!
            </div>
            {% endif %}
            {% if has_avatar == False %}
            <div class="alert-warning">
              <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
              Você precisa adicionar sua foto de perfil!<br /> <a href="" >Adicionar</a>
            </div>
            {% endif %}
					</div>
					<!-- /THREAD TITLE -->
					<!-- /COMMENTS -->
				</div>
					</div>
					<!-- /PRODUCT LIST -->
				</div>
				<!-- /PRODUCT SHOWCASE -->

				<div class="clearfix"></div>

			</div>
			<!-- CONTENT -->

      {% include 'sidebar.html' %}

		</div>
	</div>
	<!-- FOOTER -->
	<footer>
		<!-- FOOTER TOP -->
		<div id="footer-top-wrap">
			<div id="footer-top">
				<!-- COMPANY INFO -->
				<div class="company-info">
					<figure class="logo small">
                        <img src="{% static 'core/images/logo_full.png' %}" alt="logo-small">
					</figure>
					<p>Nós vamos mostrar o caminho para inovar a busca para encontrar profissionais de forma clara e segura que vão deixar sua casa perfeita.</p>
					<!-- SOCIAL LINKS -->
					<ul class="social-links">
						<li class="social-link fb">
							<a href="https://www.facebook.com/profissade"></a>
						</li>
					</ul>
					<!-- /SOCIAL LINKS -->
                    <div class="link-info">
					<!-- /LINK LIST -->
				</div>
				</div>
				<!-- /COMPANY INFO -->
                <div class="link-info">
					<p class="footer-title">Nossa comunidade</p>
					<!-- LINK LIST -->
					<ul class="link-list">
						<li class="link-item">
							<div class="bullet"></div>
							<a href="">Quem somos?</a>
						</li>
						<li class="link-item">
							<div class="bullet"></div>
							<a href="">Como funciona?</a>
						</li>
						<li class="link-item">
							<div class="bullet"></div>
							<a href="">Quem são os profissionais?</a>
						</li>
						<li class="link-item">
							<div class="bullet"></div>
							<a href="blog-v1.html">Confiança e Segurança</a>
						</li>
					</ul>
					<!-- /LINK LIST -->
				</div>
			</div>
		</div>
		<!-- /FOOTER TOP -->

		<!-- FOOTER BOTTOM -->
		<div id="footer-bottom-wrap">
			<div id="footer-bottom">
				<p>profissa.de - A melhor plataforma para profissionais de casa & construção - 2017</p>
			</div>
		</div>
		<!-- /FOOTER BOTTOM -->
	</footer>
	<!-- /FOOTER -->
{% endblock %}

core/templates/header.html
{% load static  %}
<!-- HEADER -->
	<div class="header-wrap">

		<header>
			<!-- LOGO -->
            <a href="{% url 'root:core' %}">
				<figure class="logo">
                    <img src="{% static 'core/images/logo_full.png' %}" alt="logo">
				</figure>
			</a>
			<!-- /LOGO -->

			<!-- LOGO MOBILE -->
            <a href="{% url 'root:core' %}">
				<figure class="logo-mobile">
                    <img src="{% static 'core/images/logo_full.png' %}" alt="logo">
				</figure>
			</a>
			<!-- /LOGO MOBILE -->

			<!-- MOBILE ACCOUNT OPTIONS HANDLER -->
			<div class="mobile-account-options-handler right secondary">
                {%  if request.user.is_authenticated   %}
						<figure class="user-avatar" style="margin-top:20px;">
                            {% if request.user.profile.avatar %}
                            <img src="{{ request.user.profile.avatar.url  }}" alt="avatar">
                            {% else %}
                            <img src="http://via.placeholder.com/50x50">
                            {% endif %}
						</figure>
                {% else %}
                <span class="icon-user"></span>
                {% endif %}
			</div>
			<!-- /MOBILE ACCOUNT OPTIONS HANDLER -->

			<!-- USER BOARD -->
			<div class="user-board">
            {% if request.user.is_authenticated %}
				<!-- USER QUICKVIEW -->
				<div class="user-quickview">
					<!-- USER AVATAR -->
					<a href="">
					<div class="outer-ring">
						<div class="inner-ring"></div>
						<figure class="user-avatar">
                            {% if request.user.profile.avatar %}
                            <img src="{{ request.user.profile.avatar.url  }}" alt="avatar">
                            {% else %}
                            <img src="http://via.placeholder.com/50x50">
                            {% endif %}
						</figure>
					</div>
					</a>
					<!-- /USER AVATAR -->

                    <!-- USER INFORMATION -->
                    <p class="user-name">{{ request.user.profile.first_name  }} {{ request.user.profile.last_name  }}</p>
					<!-- SVG ARROW -->
					<svg class="svg-arrow">
						<use xlink:href="#svg-arrow"></use>
					</svg>
					<!-- /SVG ARROW -->
					<!-- /USER INFORMATION -->

					<!-- DROPDOWN -->
					<ul class="dropdown small hover-effect closed">
						<li class="dropdown-item">
							<div class="dropdown-triangle"></div>
                            <a href="{% url 'root:profile_edit' %}">Meu Perfil</a>
						</li>
						<li class="dropdown-item">
							<div class="dropdown-triangle"></div>
                            <a href="{% url 'root:panel' %}">Painel de controle</a>
						</li>
						<li class="dropdown-item">
							<div class="dropdown-triangle"></div>
                            <a href="{% url 'root:panel' %}">Solicitação de serviços</a>
						</li>
						<li class="dropdown-item">
							<div class="dropdown-triangle"></div>
                            <a href="{% url 'root:panel' %}">Oferecer serviços</a>
						</li>
						<li class="dropdown-item">
                            <a href="{% url 'logout' %}">Sair</a>
						</li>
					</ul>
					<!-- /DROPDOWN -->
				</div>
				<!-- /USER QUICKVIEW -->
            {% else  %}
				<!-- ACCOUNT ACTIONS -->
				<div class="account-actions">
                    <a href="{% url 'accounts:register' %}">Inscrever-se</a>
                    <a href="{% url 'login'  %}">Conectar-se</a>
                    <a href="{% url 'provider' %}" class="button secondary">Oferecer serviço</a>
				</div>
				<!-- /ACCOUNT ACTIONS -->
            {% endif  %}
			</div>
            <!-- /USER BOARD -->
        </header>

	</div>
	<!-- /HEADER -->

	<!-- SIDE MENU -->
	<div id="account-options-menu" class="side-menu right closed">
		<!-- SVG PLUS -->

        {% if request.user.is_authenticated %}
		<!-- SIDE MENU HEADER -->
        <svg class="svg-plus">
			<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-plus"></use>
		</svg>
		<!-- /SVG PLUS -->
		<div class="side-menu-header">
			<!-- USER QUICKVIEW -->
			<!-- /USER QUICKVIEW -->
		</div>
		<!-- /SIDE MENU HEADER -->

		<!-- DROPDOWN -->
		<ul class="dropdown dark hover-effect">
			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
                <a href="{% url 'root:profile_edit' %}">Meu perfil</a>
			</li>
			<!-- /DROPDOWN ITEM -->
			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
                <a href="{% url 'root:panel' %}">Painel de controle</a>
			</li>
			<!-- /DROPDOWN ITEM -->
			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
                <a href="{% url 'root:panel' %}">Solicitação de serviços</a>
			</li>
			<!-- /DROPDOWN ITEM -->
			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
                <a href="{% url 'root:panel' %}">Oferecer serviços</a>
			</li>
			<!-- /DROPDOWN ITEM -->
			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
                <a href="{% url 'logout' %}">Sair</a>
			</li>
			<!-- /DROPDOWN ITEM -->

		</ul>
		<!-- /DROPDOWN -->
		</ul>
		<!-- /DROPDOWN -->
        {% else %}
        <svg class="svg-plus">
			<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-plus"></use>
		</svg>
		<!-- /SVG PLUS -->
        <div class="side-menu-header"></div>
        <ul class="dropdown dark hover-effect">
			<!-- DROPDOWN ITEM -->
            <li class="dropdown-item">  <a href="{% url 'accounts:register' %}">Inscrever-se</a></li>
            <li class="dropdown-item">  <a href="{% url 'login'  %}">Conectar-se</a></li>
            <li class="dropdown-item">  <a href="{% url 'provider' %}">Oferecer serviços</a></li>
         </ul>

        {% endif %}
	</div>
	<!-- /SIDE MENU -->

core/templates/profile.html
{% extends 'base.html'  %}
{% load staticfiles  %}
{% block title  %} Seu painel de controle{% endblock %}
{% block content  %}

  {% include 'header.html'  %}

<div class="section-wrap">
		<div class="section">
			<!-- CONTENT -->
			<div class="content">
				<!-- HEADLINE -->
				<div class="headline secondary">
          <h4>Seu perfil</h4>
					<!-- VIEW SELECTORS -->
					<div class="view-selectors">
					</div>
					<!-- /VIEW SELECTORS -->
					<div class="clearfix"></div>
				</div>
				<!-- /HEADLINE -->

				<!-- PRODUCT SHOWCASE -->
				<div class="product-showcase">
					<!-- PRODUCT LIST -->
					<div class="product-list grid column3-4-wrap">
            <div class="thread">
					<!-- THREAD TITLE -->
					<div class="thread-title pinned">
            <p class="text-header">Suas informações pessoais</p><br />
            {% if messages %}
              {% for message in messages %}
              <div class="alert-{{ message.tags }}">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                {{ message  }}
              </div>
              {% endfor %}
            {% endif %}

            <form method="POST" enctype="multipart/form-data" class="profile-info-form">
              {% csrf_token %}
              {% for error in form.non_field_errors  %}
              <div class="alert alert-danger">
                {{ error  }}
              </div>
              {% endfor  %}

              {% for hidden in form.hidden_fields %}
              {{ hidden }}
              {% endfor %}
              {{ form  }}
              <br /><br />
                <button class="button mid-short primary">Salvar alterações</button>
              </form>
					</div>
					<!-- /THREAD TITLE -->
					<!-- /COMMENTS -->
				</div>
					</div>
					<!-- /PRODUCT LIST -->
				</div>
				<!-- /PRODUCT SHOWCASE -->

				<div class="clearfix"></div>

			</div>
			<!-- CONTENT -->

      {% include 'sidebar.html' %}

		</div>
	</div>
	<!-- FOOTER -->
	<footer>
		<!-- FOOTER TOP -->
		<div id="footer-top-wrap">
			<div id="footer-top">
				<!-- COMPANY INFO -->
				<div class="company-info">
					<figure class="logo small">
                        <img src="{% static 'core/images/logo_full.png' %}" alt="logo-small">
					</figure>
					<p>Nós vamos mostrar o caminho para inovar a busca para encontrar profissionais de forma clara e segura que vão deixar sua casa perfeita.</p>
					<!-- SOCIAL LINKS -->
					<ul class="social-links">
						<li class="social-link fb">
							<a href="https://www.facebook.com/profissade"></a>
						</li>
					</ul>
					<!-- /SOCIAL LINKS -->
                    <div class="link-info">
					<!-- /LINK LIST -->
				</div>
				</div>
				<!-- /COMPANY INFO -->
                <div class="link-info">
					<p class="footer-title">Nossa comunidade</p>
					<!-- LINK LIST -->
					<ul class="link-list">
						<li class="link-item">
							<div class="bullet"></div>
							<a href="">Quem somos?</a>
						</li>
						<li class="link-item">
							<div class="bullet"></div>
							<a href="">Como funciona?</a>
						</li>
						<li class="link-item">
							<div class="bullet"></div>
							<a href="">Quem são os profissionais?</a>
						</li>
						<li class="link-item">
							<div class="bullet"></div>
							<a href="blog-v1.html">Confiança e Segurança</a>
						</li>
					</ul>
					<!-- /LINK LIST -->
				</div>
			</div>
		</div>
		<!-- /FOOTER TOP -->

		<!-- FOOTER BOTTOM -->
		<div id="footer-bottom-wrap">
			<div id="footer-bottom">
				<p>profissa.de - A melhor plataforma para profissionais de casa & construção - 2017</p>
			</div>
		</div>
		<!-- /FOOTER BOTTOM -->
	</footer>
	<!-- /FOOTER -->
{% endblock %}

core/templates/provider_menu.html
			<li class="dropdown-item">
                <a href="{% url 'root:panel' %}">
                    <span class="sl-icon icon-layers"></span>
                    Painel
                </a>
			</li>
			<!-- /DROPDOWN ITEM -->
			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
                <a href="{% url 'root:configuration_index' %}">
                    <span class="sl-icon icon-settings"></span>
                    Configurações
                </a>
			</li>
			<!-- /DROPDOWN ITEM -->
			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
                <a href="{% url 'root:ads_index' %}">
                    <span class="sl-icon icon-basket-loaded"></span>
                    Anúncios
                </a>
			</li>
			<!-- /DROPDOWN ITEM -->

			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
				<a href="">
                    <span class="sl-icon icon-info"></span>
                    Ordens de serviço
                </a>
                <!-- PIN -->
                <span class="pin soft-edged big primary">{0}</span>
                <!-- /PIN -->
			</li>
			<!-- /DROPDOWN ITEM -->


			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
				<a href="">
                    <span class="sl-icon icon-paper-plane"></span>
                    Solicitações
                </a>
			</li>
			<!-- /DROPDOWN ITEM -->

			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
				<a href="">
                    <span class="sl-icon icon-envelope"></span>
                    Mensagens
                </a>
			</li>
			<!-- DROPDOWN ITEM -->
			<li class="dropdown-item">
				<a href="">
                    <span class="sl-icon icon-heart"></span>
                    Avaliações
                </a>
			</li>
			<!-- /DROPDOWN ITEM -->

core/templates/sidebar.html
			<!-- SIDEBAR -->
			<div class="sidebar">
				<!-- DROPDOWN -->
				<ul class="dropdown hover-effect secondary">
					<li class="dropdown-item active">
                        <a href="{% url 'root:panel' %}">Painel de controle</a>
					</li>
					<li class="dropdown-item active">
                        <a href="{% url 'root:profile_edit' %}">Meu perfil</a>
					</li>
					<li class="dropdown-item active">
                        <a href="{% url 'root:solicitations_index' %}">Solicitações de serviços</a>
					</li>
					<li class="dropdown-item active">
                        <a href="{% url 'root:ad_new' %}">Oferecer serviços</a>
					</li>
				</ul>
				<!-- /DROPDOWN -->
				<!-- SIDEBAR ITEM -->
			</div>
			<!-- /SIDEBAR -->